// 出站 SSO cmd 常量注册表 + per-platform 签名白名单 (单一真源)。
//
// 背景: 原来 cmd 字符串散落在各 mixin 里硬编码, "谁该签名"靠 client.ts 里一张
// 外部抄来的 532 条超集 allowlist 决定。这里把 cmd 收敛成带语义名的常量 (Cmd),
// 签名判定统一走 cmdNeedsSign()。
//
// 签名面积当前是**旧 532 超集** (非真机 99 条), 原因见文件末 SIGN_REQUIRED 上的注释。

import type { ProtocolName } from './profiles'

// ============================================================================
// Cmd 注册表 —— 所有 Bot 会发出的出站 cmd, 按域分组。
// 命名取自各 mixin 里发送它的方法名 (PascalCase)。
// sendOidb(0xNNN, sub) 的数字调用不直接引用这里的常量 (它内部拼字符串), 但仍在此登记,
// 供 SIGN_REQUIRED 匹配 + 文档索引。
// ============================================================================
export const Cmd = {
  // ---- 扫码 / wtlogin 登录帧 ----
  Login: {
    ScanCode: 'wtlogin.trans_emp',            // fetchQrCode (watch 走 skipSign 不签)
    Login: 'wtlogin.login',                   // pollQrCode
    DeviceLogin: 'wtlogin_device.login',
    DeviceTranSimEmp: 'wtlogin_device.tran_sim_emp',
  },

  // ---- NT 登录 ECDH (trpc.login.ecdh.*) ----
  Ecdh: {
    KeyExchange: 'trpc.login.ecdh.EcdhService.SsoKeyExchange',
    NTLoginEasyLogin: 'trpc.login.ecdh.EcdhService.SsoNTLoginEasyLogin',
    NTLoginEasyLoginUnusualDevice: 'trpc.login.ecdh.EcdhService.SsoNTLoginEasyLoginUnusualDevice',
    NTLoginPasswordLogin: 'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLogin',
    NTLoginPasswordLoginNewDevice: 'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginNewDevice',
    NTLoginPasswordLoginUnusualDevice: 'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginUnusualDevice',
    NTLoginAuthLogin: 'trpc.login.ecdh.EcdhService.SsoNTLoginAuthLogin',
    NTLoginAuthCodeLogin: 'trpc.login.ecdh.EcdhService.SsoNTLoginAuthCodeLogin',
    NTLoginRefreshTicket: 'trpc.login.ecdh.EcdhService.SsoNTLoginRefreshTicket',
    NTLoginTGTExchangeFastLogin: 'trpc.login.ecdh.EcdhService.SsoNTLoginTGTExchangeFastLogin',
    QRLoginGenQr: 'trpc.login.ecdh.EcdhService.SsoQRLoginGenQr',
    OIDB0x916a: 'trpc.login.ecdh.EcdhService.SsoOIDB0x916a',
    OIDB0x916b: 'trpc.login.ecdh.EcdhService.SsoOIDB0x916b',
    OIDB0x916c: 'trpc.login.ecdh.EcdhService.SsoOIDB0x916c',
    OIDB0x916d: 'trpc.login.ecdh.EcdhService.SsoOIDB0x916d',
    OIDB0x9689: 'trpc.login.ecdh.EcdhService.SsoOIDB0x9689',
  },

  // ---- o3 安全通道 (ESK / SecureAccess / Report) ----
  O3: {
    EstablishShareKey: 'trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey',
    SecureAccess: 'trpc.o3.ecdh_access.EcdhAccess.SsoSecureAccess',
    SecureA2Access: 'trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access',
    SecureA2Establish: 'trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish',
    Report: 'trpc.o3.report.Report.SsoReport',
  },

  // ---- 上线 / 保活 / 状态 ----
  Session: {
    InfoSync: 'trpc.msg.register_proxy.RegisterProxy.SsoInfoSync',
    Heartbeat: 'trpc.qq_new_tech.status_svc.StatusService.SsoHeartBeat',
    HeartbeatAlive: 'Heartbeat.Alive',        // type-13 层保活, 不过 sendCommand 签名门
    SetStatus: 'trpc.qq_new_tech.status_svc.StatusService.SetStatus',
    SyncFirstView: 'trpc.group_pro.synclogic.SyncLogic.SyncFirstView',
    PushAck: 'trpc.msg.olpush.OlPushService.SsoPushAck',
    PushParams: 'trpc.msg.register_proxy.RegisterProxy.PushParams',
  },

  // ---- 消息 收发 / 撤回 / 拉取 ----
  Message: {
    Send: 'MessageSvc.PbSendMsg',
    ProxySend: 'trpc.group_pro.msgproxy.sendmsg',
    SendLongMsg: 'trpc.group.long_msg_interface.MsgService.SsoSendLongMsg',
    RecvLongMsg: 'trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg',
    RecallC2C: 'trpc.msg.msg_svc.MsgService.SsoC2CRecallMsg',
    RecallGroup: 'trpc.msg.msg_svc.MsgService.SsoGroupRecallMsg',
    ReadedReport: 'trpc.msg.msg_svc.MsgService.SsoReadedReport',
    GetPeerSeq: 'trpc.msg.msg_svc.MsgService.SsoGetPeerSeq',
    GetGroupMsg: 'trpc.msg.register_proxy.RegisterProxy.SsoGetGroupMsg',
    GetC2cMsg: 'trpc.msg.register_proxy.RegisterProxy.SsoGetC2cMsg',
    GetRoamMsg: 'trpc.msg.register_proxy.RegisterProxy.SsoGetRoamMsg',
    FetchAiCharacterList: 'OidbSvcTrpcTcp.0x929d_0',
    GetGroupGenerateAiRecord: 'OidbSvcTrpcTcp.0x929b_0',
    FetchMsgEmojiLikes: 'OidbSvcTrpcTcp.0x9083_1',
    SetInputStatus: 'OidbSvcTrpcTcp.0xcd4_1',
    PullPics: 'PicSearchSvr.PullPics',
    ListFavEmojis: 'Faceroam.OpReq',
    AddFavEmojiPrep: 'ImgStore.BDHExpressionRoam',
    TransGroupPtt: 'pttTrans.TransGroupPttReq',
    TransC2CPtt: 'pttTrans.TransC2CPttReq',
  },

  // ---- 群管理 / 群文件 / 群相册 ----
  Group: {
    // sendOidb (数字调用) —— 登记供 SIGN 匹配, 发送点保持数字不迁移
    Poke: 'OidbSvcTrpcTcp.0xed3_1',
    SetSpecialTitle: 'OidbSvcTrpcTcp.0x8fc_2',
    ClockIn: 'OidbSvcTrpcTcp.0xeb7_1',
    SetRemark: 'OidbSvcTrpcTcp.0xf16_1',
    SetPin: 'OidbSvcTrpcTcp.0x5d6_1',
    KickMember: 'OidbSvcTrpcTcp.0x8a0_1',
    MuteMember: 'OidbSvcTrpcTcp.0x1253_1',
    MuteAll: 'OidbSvcTrpcTcp.0x89a_0',
    SetName: 'OidbSvcTrpcTcp.0x89a_15',
    SetMemberCard: 'OidbSvcTrpcTcp.0x8fc_3',
    SetMemberAdmin: 'OidbSvcTrpcTcp.0x1096_1',
    Leave: 'OidbSvcTrpcTcp.0x1097_1',
    // sendPB (字面量) —— 发送点迁移引用
    GetFileUrl: 'OidbSvcTrpcTcp.0x6d6_2',
    FetchGroups: 'OidbSvcTrpcTcp.0xfe5_2',
    GetFileList: 'OidbSvcTrpcTcp.0x6d8_1',
    GetFileCount: 'OidbSvcTrpcTcp.0x6d8_2',
    GetFileSpace: 'OidbSvcTrpcTcp.0x6d8_3',
    FeedFile: 'OidbSvcTrpcTcp.0x6d9_4',
    DeleteFile: 'OidbSvcTrpcTcp.0x6d6_3',
    MoveFile: 'OidbSvcTrpcTcp.0x6d6_5',
    RenameFile: 'OidbSvcTrpcTcp.0x6d6_4',
    CreateFolder: 'OidbSvcTrpcTcp.0x6d7_0',
    DeleteFolder: 'OidbSvcTrpcTcp.0x6d7_1',
    RenameFolder: 'OidbSvcTrpcTcp.0x6d7_2',
    Fetch: 'OidbSvcTrpcTcp.0x88d_14',
    FetchExtra: 'OidbSvcTrpcTcp.0x88d_0',
    FetchMembers: 'OidbSvcTrpcTcp.0xfe7_3',
    FetchAtAllRemain: 'OidbSvcTrpcTcp.0x8a7_0',
    ForwardFile: 'OidbSvcTrpcTcp.0x6d9_2',
    CreateAlbum: 'QunAlbum.trpc.qzone.webapp_qun_media.QunMedia.AddAlbum',
    DeleteAlbum: 'QunAlbum.trpc.qzone.webapp_qun_media.QunMedia.DeleteAlbum',
    FetchAlbumList: 'QunAlbum.trpc.qzone.webapp_qun_media.QunMedia.GetAlbumList',
    FetchAlbumMediaList: 'QunAlbum.trpc.qzone.webapp_qun_media.QunMedia.GetMediaList',
  },

  // ---- 好友管理 / 好友请求 ----
  Friend: {
    // sendOidb (数字调用)
    Poke: 'OidbSvcTrpcTcp.0xed3_1',
    SetRequest: 'OidbSvcTrpcTcp.0xb5d_44',
    SetFilteredRequest: 'OidbSvcTrpcTcp.0xd72_0',
    SetRemark: 'OidbSvcTrpcTcp.0x10cc_1',
    Delete: 'OidbSvcTrpcTcp.0x126b_0',
    SetCategory: 'OidbSvcTrpcTcp.0x10eb_1',
    SetPin: 'OidbSvcTrpcTcp.0x5d6_18',
    // sendPB (字面量)
    GetPrivateFileUrl: 'OidbSvcTrpcTcp.0xe37_1200',
    Fetch: 'OidbSvcTrpcTcp.0xfd4_1',
    GetRecommendContactArk: 'OidbSvcTrpcTcp.0x12b6_0',
    FetchRequests: 'OidbSvcTrpcTcp.0x5cf_11',
    FetchFilteredRequests: 'OidbSvcTrpcTcp.0xd69_0',
    GetStatus: 'OidbSvcTrpcTcp.0x116d_1',
  },

  // ---- 用户资料 / 状态 / 点赞 ----
  User: {
    SendLike: 'OidbSvcTrpcTcp.0x7e5_104',
    ModifySelfProfile: 'OidbSvcTrpcTcp.0x112a_2',
    FetchInfoByUin: 'OidbSvcTrpcTcp.0xfe1_2',
    FetchLoginDays: 'MQUpdateSvc_com_qq_ti.web.OidbSvc.0xdef_1',
    FetchClientKey: 'OidbSvcTrpcTcp.0x102a_1',
    FetchPSkey: 'OidbSvcTrpcTcp.0x102a_0',
    FetchProfileLikes: 'OidbSvcTrpcTcp.0x7ed_13',
    FetchProfileLikeCount: 'OidbSvcTrpcTcp.0x7ed_12',
  },

  // ---- 富媒体 上传 / 下载 / highway / 闪传 ----
  Media: {
    GetRKey: 'OidbSvcTrpcTcp.0x9067_202',
    GetHighwaySession: 'HttpConn.0x6ff_501',
    GetPrivatePttUrl: 'OidbSvcTrpcTcp.0x126d_200',
    GetGroupPttUrl: 'OidbSvcTrpcTcp.0x126e_200',
    GetGroupVideoUrl: 'OidbSvcTrpcTcp.0x11ea_200',
    GetPrivateVideoUrl: 'OidbSvcTrpcTcp.0x11e9_200',
    NotifyGroupVideoUploadCompleted: 'OidbSvcTrpcTcp.0x11ea_100',
    GetC2CVideoUploadInfo: 'OidbSvcTrpcTcp.0x11e9_100',
    GetGroupFileUploadInfo: 'OidbSvcTrpcTcp.0x6d6_0',
    GetC2CFileUploadInfo: 'OidbSvcTrpcTcp.0xe37_1700',
    GetGroupImageUploadInfo: 'OidbSvcTrpcTcp.0x11c4_100',
    GetC2CImageUploadInfo: 'OidbSvcTrpcTcp.0x11c5_100',
    GetGroupPttUploadInfo: 'OidbSvcTrpcTcp.0x126e_100',
    GetC2CPttUploadInfo: 'OidbSvcTrpcTcp.0x126d_100',
    ImageOcr: 'OidbSvcTrpcTcp.0xe07_0',
    GetFlashFileSetIdByCode: 'OidbSvcTrpcTcp.0x93eb_1',
    GetFlashFileInfo: 'OidbSvcTrpcTcp.0x93d3_1',
    GetFlashFileList: 'OidbSvcTrpcTcp.0x93d4_1',
    GetFlashFileEntryFull: 'OidbSvcTrpcTcp.0x93e5_4',
    DownloadFlashFile: 'OidbSvcTrpcTcp.0x93d1_1',
    CreateFlashFileSet: 'OidbSvcTrpcTcp.0x93cf_1',
    RegisterFlashFile: 'OidbSvcTrpcTcp.0x93d0_1',
    PrepFlashFileSet: 'OidbSvcTrpcTcp.0x93db_1',
    FlashFileUploadPreflight: 'OidbSvcTrpcTcp.0x12a9_100',
    FlashFileUploadCommitReport: 'OidbSvcTrpcTcp.0x12a9_103',
    FlashFileUploadCommit: 'OidbSvcTrpcTcp.0x12a9_200',
  },

  // ---- 杂项 ----
  Misc: {
    FetchPins: 'OidbSvcTrpcTcp.0x12b3_0',
  },
} as const

// ============================================================================
// 真机签名白名单 (ground-truth)
// ============================================================================

// Linux 真机 sub_56D2D00 静态白名单 97 条 —— IDA 逆向自 wrapper.node 3.2.28-48517。
// 来源与门控机制见 LuckyLillia.Sign/docs/Linux/algorithm/QQ-3.2.28-48517.md
// ("Sign cmd 白名单" 一节)。真机发包主循环每个出站 cmd 都过 IsNeedSignCmd, 不在名单
// 里的裸发不签。
const LINUX_STATIC_SIGN: readonly string[] = [
  'ConnAuthSvr.fast_qq_login',
  'ConnAuthSvr.sdk_auth_api',
  'ConnAuthSvr.sdk_auth_api_emp',
  'MessageSvc.PbSendMsg',
  'MsgProxy.SendMsg',
  'OidbSvc.0xb77_9',
  'OidbSvc.0xcd5',
  'OidbSvc.0xdc2_34',
  'OidbSvcTrpcTcp.0x101b_1',
  'OidbSvcTrpcTcp.0x101e_1',
  'OidbSvcTrpcTcp.0x101e_2',
  'OidbSvcTrpcTcp.0x102a_0',
  'OidbSvcTrpcTcp.0x102a_1',
  'OidbSvcTrpcTcp.0x10c8_1',
  'OidbSvcTrpcTcp.0x10c8_2',
  'OidbSvcTrpcTcp.0x10db_1',
  'OidbSvcTrpcTcp.0x1100_1',
  'OidbSvcTrpcTcp.0x1102_1',
  'OidbSvcTrpcTcp.0x1103_1',
  'OidbSvcTrpcTcp.0x1105_1',
  'OidbSvcTrpcTcp.0x1107_1',
  'OidbSvcTrpcTcp.0x112a_1',
  'OidbSvcTrpcTcp.0x112a_2',
  'OidbSvcTrpcTcp.0x112e_1',
  'OidbSvcTrpcTcp.0x11ec_1',
  'OidbSvcTrpcTcp.0x587_74',
  'OidbSvcTrpcTcp.0x6d9_4',
  'OidbSvcTrpcTcp.0x758_1',
  'OidbSvcTrpcTcp.0x7c2_5',
  'OidbSvcTrpcTcp.0x88d_0',
  'OidbSvcTrpcTcp.0x88d_14',
  'OidbSvcTrpcTcp.0x89a_0',
  'OidbSvcTrpcTcp.0x89a_15',
  'OidbSvcTrpcTcp.0x8a1_7',
  'OidbSvcTrpcTcp.0x917b_1',
  'OidbSvcTrpcTcp.0x93d7_1',
  'OidbSvcTrpcTcp.0x9409_10',
  'OidbSvcTrpcTcp.0x9409_11',
  'OidbSvcTrpcTcp.0x9409_12',
  'OidbSvcTrpcTcp.0x9409_13',
  'OidbSvcTrpcTcp.0x9409_14',
  'OidbSvcTrpcTcp.0x9409_15',
  'OidbSvcTrpcTcp.0x9409_16',
  'OidbSvcTrpcTcp.0x9409_18',
  'OidbSvcTrpcTcp.0x9409_7',
  'OidbSvcTrpcTcp.0x962a_1',
  'OidbSvcTrpcTcp.0xcd5',
  'OidbSvcTrpcTcp.0xcd5_0',
  'OidbSvcTrpcTcp.0xdc2_58',
  'OidbSvcTrpcTcp.0xdc2_59',
  'OidbSvcTrpcTcp.0xf55_1',
  'OidbSvcTrpcTcp.0xf57_1',
  'OidbSvcTrpcTcp.0xf57_106',
  'OidbSvcTrpcTcp.0xf57_9',
  'OidbSvcTrpcTcp.0xf65_1',
  'OidbSvcTrpcTcp.0xf65_10',
  'OidbSvcTrpcTcp.0xf67_1',
  'OidbSvcTrpcTcp.0xf67_5',
  'OidbSvcTrpcTcp.0xf6e_1',
  'OidbSvcTrpcTcp.0xf88_1',
  'OidbSvcTrpcTcp.0xf89_1',
  'OidbSvcTrpcTcp.0xfa5_1',
  'QQConnectLogin.auth',
  'QQConnectLogin.pre_auth',
  'trpc.ecom.api_gateway.ApiGateway.SsoForward',
  'trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg',
  'trpc.group.long_msg_interface.MsgService.SsoSendLongMsg',
  'trpc.group_pro.msgproxy.sendmsg',
  'trpc.login.ecdh.EcdhService.SsoKeyExchange',
  'trpc.login.ecdh.EcdhService.SsoNTLoginAuthCodeLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginAuthLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginEasyLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginEasyLoginUnusualDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginNewDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginUnusualDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginRefreshTicket',
  'trpc.login.ecdh.EcdhService.SsoNTLoginTGTExchangeFastLogin',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916a',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916b',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916c',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916d',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x9689',
  'trpc.login.ecdh.EcdhService.SsoQRLoginGenQr',
  'trpc.msg.msg_svc.MsgService.SsoC2CRecallMsg',
  'trpc.msg.msg_svc.MsgService.SsoReadedReport',
  'trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey',
  'trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access',
  'trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish',
  'trpc.o3.ecdh_access.EcdhAccess.SsoSecureAccess',
  'trpc.o3.report.Report.SsoReport',
  'trpc.passwd.manager.PasswdManager.SetPasswd',
  'trpc.passwd.manager.PasswdManager.VerifyPasswd',
  'trpc.qqhb.qqhb_proxy.Handler.sso_handle',
  'wtlogin.login',
  'wtlogin.trans_emp',
  'wtlogin_device.login',
  'wtlogin_device.tran_sim_emp',
  'OidbSvcTcp.0x102a',
]

// 旧的 532 条超集 (2026-07-06 ~ 09-21 在用, 697592df 收敛时删掉), 2026-10-09 整份恢复。
// 99 条真机 ground-truth 留在 LINUX_STATIC_SIGN 不动, 要切回只改下面 EFFECTIVE_SIGN。
const LEGACY_SIGN_SUPERSET: readonly string[] = [
  'AvatarInfoSvr.QQHeadUrlReq',
  'CertifiedAccountSvc.certified_account_read.GetFollowList',
  'ConfigPushSvc.PushResp',
  'ConnAuthSvr.fast_qq_login',
  'ConnAuthSvr.get_app_info',
  'ConnAuthSvr.get_app_info_emp',
  'ConnAuthSvr.get_auth_api_list',
  'ConnAuthSvr.get_auth_api_list_emp',
  'ConnAuthSvr.sdk_auth_api',
  'ConnAuthSvr.sdk_auth_api_emp',
  'FeedCloudSvr.trpc.circlesearch.exhibition.ExhibitionSvr.ExhibitionSuggestion',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetBusiInfo',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetCommentList',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetFeedList',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetMainPageBasicData',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetMainPageCommData',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetRelationGroupList',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetReplyList',
  'FeedCloudSvr.trpc.feedcloud.commreader.ComReader.GetRerankedFeedList',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoBarrage',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoComment',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoFollow',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoLike',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoPush',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.DoReply',
  'FeedCloudSvr.trpc.feedcloud.commwriter.ComWriter.PublishFeed',
  'FeedCloudSvr.trpc.videocircle.circleprofile.CircleProfile.SetProfile',
  'GameCenterMsg.GetUserInfo',
  'HttpConn.0x6ff_501',
  'IncreaseURLSvr.QQHeadUrlReq',
  'LightAppSvc.mini_app_cloudstorage.GetUserCloudStorage',
  'LightAppSvc.mini_app_privacy.GetPrivacyInfo',
  'LightAppSvc.mini_app_userapp.GetDropdownAppList',
  'MQUpdateSvc_com_qq_qzone_act.web.OidbSvcTrpcJsapiTcp.0x9377_0',
  'MQUpdateSvc_com_qq_ti.web.OidbSvcTrpcJsapiTcp.0x9044_0',
  'MQUpdateSvc_com_qq_ti.web.OidbSvcTrpcJsapiTcp.0x9047_0',
  'MQUpdateSvc_com_qq_ti.web.OidbSvcTrpcJsapiTcp.0x9172_0',
  'MessageSvc.PbBindUinGetMsg',
  'MessageSvc.PbGetGroupMsg',
  'MessageSvc.PbGetMsg',
  'MessageSvc.PbGetRoamMsg',
  'MessageSvc.PbSendMsg',
  'MsgProxy.SendMsg',
  'NowSummaryCard.NearbyMiniCardReq',
  'OidbSvc.0x42d',
  'OidbSvc.0x42d_4',
  'OidbSvc.0x480_9',
  'OidbSvc.0x480_9_IMCore',
  'OidbSvc.0x4ff_9',
  'OidbSvc.0x4ff_9_IMCore',
  'OidbSvc.0x515_2',
  'OidbSvc.0x53c_2',
  'OidbSvc.0x56c_6',
  'OidbSvc.0x570_8',
  'OidbSvc.0x580_1',
  'OidbSvc.0x587_123',
  'OidbSvc.0x587_normalNightSet',
  'OidbSvc.0x58b',
  'OidbSvc.0x592',
  'OidbSvc.0x592_1',
  'OidbSvc.0x592_10',
  'OidbSvc.0x592_11',
  'OidbSvc.0x592_12',
  'OidbSvc.0x592_13',
  'OidbSvc.0x592_15',
  'OidbSvc.0x592_16',
  'OidbSvc.0x592_17',
  'OidbSvc.0x592_18',
  'OidbSvc.0x592_19',
  'OidbSvc.0x592_2',
  'OidbSvc.0x592_3',
  'OidbSvc.0x592_4',
  'OidbSvc.0x592_5',
  'OidbSvc.0x592_6',
  'OidbSvc.0x592_7',
  'OidbSvc.0x592_8',
  'OidbSvc.0x592_9',
  'OidbSvc.0x59f',
  'OidbSvc.0x5d0_1',
  'OidbSvc.0x5eb_15',
  'OidbSvc.0x5eb_22',
  'OidbSvc.0x5eb_42073',
  'OidbSvc.0x5eb_42261',
  'OidbSvc.0x5eb_43',
  'OidbSvc.0x5eb_96',
  'OidbSvc.0x5eb_99',
  'OidbSvc.0x5eb_ForTheme',
  'OidbSvc.0x5eb_cn_switch',
  'OidbSvc.0x5eb_common',
  'OidbSvc.0x6d6_0',
  'OidbSvc.0x6d6_2',
  'OidbSvc.0x6d6_3',
  'OidbSvc.0x6d7_0',
  'OidbSvc.0x6d9_4',
  'OidbSvc.0x6de',
  'OidbSvc.0x758',
  'OidbSvc.0x758_0',
  'OidbSvc.0x758_1',
  'OidbSvc.0x787_0',
  'OidbSvc.0x787_1',
  'OidbSvc.0x787_11',
  'OidbSvc.0x7a2_0',
  'OidbSvc.0x7df_3',
  'OidbSvc.0x852_35',
  'OidbSvc.0x852_48',
  'OidbSvc.0x88d_0',
  'OidbSvc.0x88d_1',
  'OidbSvc.0x88d_1_2',
  'OidbSvc.0x88d_7',
  'OidbSvc.0x899_0',
  'OidbSvc.0x899_9',
  'OidbSvc.0x89a_0',
  'OidbSvc.0x89b_1',
  'OidbSvc.0x8a0_0',
  'OidbSvc.0x8a1_0',
  'OidbSvc.0x8a1_7',
  'OidbSvc.0x8a4',
  'OidbSvc.0x8a8',
  'OidbSvc.0x8ba',
  'OidbSvc.0x8f1',
  'OidbSvc.0x9fa',
  'OidbSvc.0xb3c',
  'OidbSvc.0xb3c_1',
  'OidbSvc.0xb3c_2',
  'OidbSvc.0xb3c_3',
  'OidbSvc.0xb3c_4',
  'OidbSvc.0xb3c_5',
  'OidbSvc.0xb3c_6',
  'OidbSvc.0xb3c_7',
  'OidbSvc.0xb3c_8',
  'OidbSvc.0xb3c_add',
  'OidbSvc.0xb3c_delete',
  'OidbSvc.0xb3c_get_by_id',
  'OidbSvc.0xb3c_get_done',
  'OidbSvc.0xb3c_get_done_count',
  'OidbSvc.0xb3c_get_undone',
  'OidbSvc.0xb3c_share',
  'OidbSvc.0xb3c_update',
  'OidbSvc.0xb3c_update_5',
  'OidbSvc.0xb77_34',
  'OidbSvc.0xb77_46',
  'OidbSvc.0xb77_48',
  'OidbSvc.0xb77_9',
  'OidbSvc.0xbbb',
  'OidbSvc.0xbcb',
  'OidbSvc.0xbe8',
  'OidbSvc.0xc26_0',
  'OidbSvc.0xc33_42220',
  'OidbSvc.0xc6b',
  'OidbSvc.0xcd5',
  'OidbSvc.0xcdd',
  'OidbSvc.0xd69',
  'OidbSvc.0xdc2_34',
  'OidbSvc.0xdc2_9',
  'OidbSvc.0xe27',
  'OidbSvc.0xe3e',
  'OidbSvc.0xe61',
  'OidbSvc.0xe63_1',
  'OidbSvc.0xe72',
  'OidbSvc.0xef0_1',
  'OidbSvc.0xf7e_1',
  'OidbSvc.oidb_0x758',
  'OidbSvcTRPCTcp.0x758_1',
  'OidbSvcTRPCTcp.0xf67_1',
  'OidbSvcTcp.0x102a',
  'OidbSvcTcp.0x88d_0',
  'OidbSvcTcp.0x88d_1',
  'OidbSvcTcp.0xef0_1',
  'OidbSvcTrpcTcp.0x1017_1',
  'OidbSvcTrpcTcp.0x101b_1',
  'OidbSvcTrpcTcp.0x101e_1',
  'OidbSvcTrpcTcp.0x101e_2',
  'OidbSvcTrpcTcp.0x102a_0',
  'OidbSvcTrpcTcp.0x102a_1',
  'OidbSvcTrpcTcp.0x102a_3',
  'OidbSvcTrpcTcp.0x105b_1',
  'OidbSvcTrpcTcp.0x1092_0',
  'OidbSvcTrpcTcp.0x10c0_1',
  'OidbSvcTrpcTcp.0x10c0_2',
  'OidbSvcTrpcTcp.0x10c8_1',
  'OidbSvcTrpcTcp.0x10c8_2',
  'OidbSvcTrpcTcp.0x10d8_1',
  'OidbSvcTrpcTcp.0x10db_1',
  'OidbSvcTrpcTcp.0x10e4_1',
  'OidbSvcTrpcTcp.0x10ed_1',
  'OidbSvcTrpcTcp.0x10f4_1',
  'OidbSvcTrpcTcp.0x1100_1',
  'OidbSvcTrpcTcp.0x1102_1',
  'OidbSvcTrpcTcp.0x1103_1',
  'OidbSvcTrpcTcp.0x1105_1',
  'OidbSvcTrpcTcp.0x1107_1',
  'OidbSvcTrpcTcp.0x110d_1',
  'OidbSvcTrpcTcp.0x112a_1',
  'OidbSvcTrpcTcp.0x112a_2',
  'OidbSvcTrpcTcp.0x112e_1',
  'OidbSvcTrpcTcp.0x1130_1',
  'OidbSvcTrpcTcp.0x116c_1',
  'OidbSvcTrpcTcp.0x116d_1',
  'OidbSvcTrpcTcp.0x1194_1',
  'OidbSvcTrpcTcp.0x11c4_100',
  'OidbSvcTrpcTcp.0x11c4_200',
  'OidbSvcTrpcTcp.0x11c5_100',
  'OidbSvcTrpcTcp.0x11c5_200',
  'OidbSvcTrpcTcp.0x11e9_100',
  'OidbSvcTrpcTcp.0x11e9_200',
  'OidbSvcTrpcTcp.0x11ea_200',
  'OidbSvcTrpcTcp.0x11ec_1',
  'OidbSvcTrpcTcp.0x121e_0',
  'OidbSvcTrpcTcp.0x1224_0',
  'OidbSvcTrpcTcp.0x1225_0',
  'OidbSvcTrpcTcp.0x123c_1',
  'OidbSvcTrpcTcp.0x1250_0',
  'OidbSvcTrpcTcp.0x1258_1',
  'OidbSvcTrpcTcp.0x125b_500',
  'OidbSvcTrpcTcp.0x1262_19',
  'OidbSvcTrpcTcp.0x126d_200',
  'OidbSvcTrpcTcp.0x126e_200',
  'OidbSvcTrpcTcp.0x1277_0',
  'OidbSvcTrpcTcp.0x127a_0',
  'OidbSvcTrpcTcp.0x1289_1',
  'OidbSvcTrpcTcp.0x12a9_200',
  'OidbSvcTrpcTcp.0x12b1_0',
  'OidbSvcTrpcTcp.0x55f_0',
  'OidbSvcTrpcTcp.0x587_74',
  'OidbSvcTrpcTcp.0x5cf_11',
  'OidbSvcTrpcTcp.0x644_1',
  'OidbSvcTrpcTcp.0x6d6_2',
  'OidbSvcTrpcTcp.0x6d6_3',
  'OidbSvcTrpcTcp.0x6d8_1',
  'OidbSvcTrpcTcp.0x6d9_2',
  'OidbSvcTrpcTcp.0x6d9_4',
  'OidbSvcTrpcTcp.0x758_1',
  'OidbSvcTrpcTcp.0x787_1',
  'OidbSvcTrpcTcp.0x7c1_1',
  'OidbSvcTrpcTcp.0x7c2_5',
  'OidbSvcTrpcTcp.0x88d_0',
  'OidbSvcTrpcTcp.0x88d_111',
  'OidbSvcTrpcTcp.0x88d_14',
  'OidbSvcTrpcTcp.0x899_0',
  'OidbSvcTrpcTcp.0x899_1',
  'OidbSvcTrpcTcp.0x899_9',
  'OidbSvcTrpcTcp.0x89a_0',
  'OidbSvcTrpcTcp.0x89a_15',
  'OidbSvcTrpcTcp.0x8a0_1',
  'OidbSvcTrpcTcp.0x8a1_7',
  'OidbSvcTrpcTcp.0x8f9_14',
  'OidbSvcTrpcTcp.0x8fc_3',
  'OidbSvcTrpcTcp.0x901f_1',
  'OidbSvcTrpcTcp.0x902e_1',
  'OidbSvcTrpcTcp.0x9076_1',
  'OidbSvcTrpcTcp.0x9078_1',
  'OidbSvcTrpcTcp.0x9079_1',
  'OidbSvcTrpcTcp.0x911a_19',
  'OidbSvcTrpcTcp.0x911a_22',
  'OidbSvcTrpcTcp.0x9124_0',
  'OidbSvcTrpcTcp.0x9127_1',
  'OidbSvcTrpcTcp.0x9144_1',
  'OidbSvcTrpcTcp.0x9176_1',
  'OidbSvcTrpcTcp.0x917b_1',
  'OidbSvcTrpcTcp.0x91b6_1',
  'OidbSvcTrpcTcp.0x929b_0',
  'OidbSvcTrpcTcp.0x92d5_0',
  'OidbSvcTrpcTcp.0x92e3_0',
  'OidbSvcTrpcTcp.0x92e4_0',
  'OidbSvcTrpcTcp.0x92eb_0',
  'OidbSvcTrpcTcp.0x930d_0',
  'OidbSvcTrpcTcp.0x930e_0',
  'OidbSvcTrpcTcp.0x93d7_1',
  'OidbSvcTrpcTcp.0x9409_10',
  'OidbSvcTrpcTcp.0x9409_11',
  'OidbSvcTrpcTcp.0x9409_12',
  'OidbSvcTrpcTcp.0x9409_13',
  'OidbSvcTrpcTcp.0x9409_14',
  'OidbSvcTrpcTcp.0x9409_15',
  'OidbSvcTrpcTcp.0x9409_16',
  'OidbSvcTrpcTcp.0x9409_18',
  'OidbSvcTrpcTcp.0x9409_7',
  'OidbSvcTrpcTcp.0x9559_0',
  'OidbSvcTrpcTcp.0x955f_1',
  'OidbSvcTrpcTcp.0x9560_1',
  'OidbSvcTrpcTcp.0x962a_1',
  'OidbSvcTrpcTcp.0x9689_1',
  'OidbSvcTrpcTcp.0x972_6',
  'OidbSvcTrpcTcp.0x9a2_12',
  'OidbSvcTrpcTcp.0x9a2_8',
  'OidbSvcTrpcTcp.0xa80_1',
  'OidbSvcTrpcTcp.0xaf6_0',
  'OidbSvcTrpcTcp.0xb77_57',
  'OidbSvcTrpcTcp.0xcd5',
  'OidbSvcTrpcTcp.0xdc2_34',
  'OidbSvcTrpcTcp.0xe37_1200',
  'OidbSvcTrpcTcp.0xe37_1700',
  'OidbSvcTrpcTcp.0xe37_700',
  'OidbSvcTrpcTcp.0xe37_800',
  'OidbSvcTrpcTcp.0xf55_1',
  'OidbSvcTrpcTcp.0xf57_1',
  'OidbSvcTrpcTcp.0xf57_106',
  'OidbSvcTrpcTcp.0xf57_9',
  'OidbSvcTrpcTcp.0xf59_1',
  'OidbSvcTrpcTcp.0xf59_2',
  'OidbSvcTrpcTcp.0xf5b_1',
  'OidbSvcTrpcTcp.0xf5d_1',
  'OidbSvcTrpcTcp.0xf5d_11',
  'OidbSvcTrpcTcp.0xf65_1',
  'OidbSvcTrpcTcp.0xf65_10',
  'OidbSvcTrpcTcp.0xf67_1',
  'OidbSvcTrpcTcp.0xf67_5',
  'OidbSvcTrpcTcp.0xf6e_1',
  'OidbSvcTrpcTcp.0xf88_1',
  'OidbSvcTrpcTcp.0xf89_1',
  'OidbSvcTrpcTcp.0xfa5_1',
  'OidbSvcTrpcTcp.0xfc9_1',
  'OidbSvcTrpcTcp.0xfd4_1',
  'OidbSvcTrpcTcp.0xfe1',
  'OidbSvcTrpcTcp.0xfe1_2',
  'OidbSvcTrpcTcp.0xfe1_8',
  'OidbSvcTrpcTcp.0xfe4_2',
  'OidbSvcTrpcTcp.0xfe5_2',
  'OidbSvcTrpcTcp.0xfe7_2',
  'OidbSvcTrpcTcp.0xfe7_3',
  'OidbSvcTrpcTcp.0xfe7_4',
  'OidbSvc_device.0x633',
  'OidbSvc_device.0x9f5',
  'PbMessageSvc.PbUnReadMsgSeq',
  'ProfileService.GetSimpleInfo',
  'ProfileService.GroupMngReq',
  'ProfileService.Pb.ReqSystemMsgAction.Group',
  'ProfileService.Pb.ReqSystemMsgNew.Group',
  'ProfileService.ReqBatchProcess',
  'ProfileService.SimpleInfo',
  'ProfileService.getGroupInfoReq',
  'PttStore.GroupPttDown',
  'PubAccountSvc.get_follow_list',
  'PushService.settoken',
  'QChannelSvr.trpc.qchannel.commreader.ComReader.BatchGetFeedDetail',
  'QChannelSvr.trpc.qchannel.commwriter.ComWriter.DoComment',
  'QChannelSvr.trpc.qchannel.commwriter.ComWriter.DoReply',
  'QChannelSvr.trpc.qchannel.commwriter.ComWriter.PublishFeed',
  'QQAIOMediaSvc.share_trans_check',
  'QQConnectLogin.auth',
  'QQConnectLogin.auth_emp',
  'QQConnectLogin.get_promote_page',
  'QQConnectLogin.get_promote_page_emp',
  'QQConnectLogin.pre_auth',
  'QQConnectLogin.pre_auth_emp',
  'QQConnectLogin.submit_promote_page',
  'QQConnectLogin.submit_promote_page_emp',
  'QQLBSShareSvc.room_operation',
  'QQRTCSvc.RoomManager-GetRoomInfo',
  'QQStranger.FeedPlazaSvr.SsoFeedPublish',
  'QQStranger.FeedSvr.SsoFeedPublish',
  'QQStranger.InteractiveMsgSvr.SsoSendInterMsg',
  'QQStranger.UserInfo.SsoBatchGetMiniUserInfo',
  'QQStranger.UserInfo.SsoGetMiniUserInfo',
  'QQStranger.UserInfo.SsoSetMiniUserInfo',
  'QQStranger.login_svr.SsoLoginInfoReport',
  'QSec.AVEng',
  'RegPrxySvc.infoLogin',
  'RegPrxySvc.infoSync',
  'ResourceConfig.ClientReq',
  'ResourceConfig.GetResourceReq',
  'SQQzoneSvc.Custom.getFacade',
  'SQQzoneSvc.GetCate',
  'SQQzoneSvc.addComment',
  'SQQzoneSvc.addReply',
  'SQQzoneSvc.elaborateFeedReport',
  'SQQzoneSvc.forward',
  'SQQzoneSvc.get',
  'SQQzoneSvc.getAIONewestFeeds',
  'SQQzoneSvc.getActiveFeeds',
  'SQQzoneSvc.getMainPage',
  'SQQzoneSvc.getPhotoComment',
  'SQQzoneSvc.getPhotoWall',
  'SQQzoneSvc.getProfile',
  'SQQzoneSvc.getProfileFeeds',
  'SQQzoneSvc.getUndealCount',
  'SQQzoneSvc.getVisitorNotify',
  'SQQzoneSvc.get_all_feedsphoto_ex',
  'SQQzoneSvc.like',
  'SQQzoneSvc.mobileqboss.get',
  'SQQzoneSvc.photo',
  'SQQzoneSvc.preGetPassiveFeeds',
  'SQQzoneSvc.publishmood',
  'SQQzoneSvc.shuoshuo',
  'SecuritySvc.GetConfig',
  'SsoSnsSession.Cmd0x3_SubCmd0x1_FuncGetBlockList',
  'StatSvc.GetDevLoginInfo',
  'StatSvc.GetOnlineStatus',
  'StatSvc.SetStatusFromClient',
  'StatSvc.SimpleGet',
  'StatSvc.register',
  'SummaryCard.ReqSummaryCard',
  'VisitorSvc.ReqDeleteVisitorRecord',
  'VisitorSvc.ReqFavorite',
  'WalletGestureSvc.GetPassword',
  'WalletGestureSvc.GetSignV2',
  'WalletGestureSvc.SetPassword',
  'account.RequestQueryQQMobileContactsV3',
  'friendlist.AddFriendReq',
  'friendlist.GetFriendListReq',
  'friendlist.GetLastLoginInfoReq',
  'friendlist.GetMultiTroopInfoReq',
  'friendlist.GetSimpleOnlineFriendInfoReq',
  'friendlist.GetTroopAppointRemarkReq',
  'friendlist.GetTroopListReqV2',
  'friendlist.GetTroopMemberList',
  'friendlist.GetTroopMemberListReq',
  'friendlist.ModifyGroupInfoReq',
  'friendlist.addFriend',
  'friendlist.getFriendGroupList',
  'friendlist.getTroopMemberList',
  'gcbindgroupsso.get_appid',
  'gcbindgroupsso.unbind_group',
  'group_member_card.get_group_member_card_info',
  'group_member_statistic.get_group_member_statistic',
  'miniapp.trpc.minigame.sdk_qgroup_svr.sdk_qgroup_svr.JoinGroup',
  'oidb_0x42e_3',
  'oidb_0x43c_4',
  'oidb_0x43c_5',
  'oidb_0x5d0_1',
  'oidb_0x5d6_19',
  'oidb_0x5d6_21',
  'oidb_0x7a2_0',
  'oidb_0x7c4_0',
  'oidb_0x7df_3',
  'oidb_0x9045_1',
  'oidb_0x9072_0',
  'oidb_0xcf3_0',
  'oidb_0xcf4_0',
  'oidb_0xd9c_11',
  'oidb_0xdc2_34',
  'oidb_0xe37_1200',
  'oidb_0xe37_800',
  'oidb_0xe61_1',
  'oidb_0xe8c_0',
  'oidb_0xeb1_1',
  'oidb_0xf7e_1',
  'oidb_0xfd4_1',
  'qidianservice.135',
  'qidianservice.207',
  'qidianservice.269',
  'qidianservice.290',
  'qzoneh5.h5.wnshtml',
  'trpc.QQService.CommonLogic.StatusService.SsoGetLikeList',
  'trpc.commercial.dataworks.UserActionReport_sso.SsoReport',
  'trpc.down.intercept.Intercept.SsoGetDownloadTips',
  'trpc.down.intercept.Intercept.SsoGetInterceptFile',
  'trpc.down.joint_operation_game_intercept.JointOperationGameIntercept.SsoCheck',
  'trpc.down.joint_operation_game_intercept.JointOperationGameIntercept.SsoQueryConfig',
  'trpc.ecom.api_gateway.ApiGateway.SsoForward',
  'trpc.g_qqrtc.qq_mav_room_state_read.GetRoomState.SsoGetInfoByUin',
  'trpc.gc_indust.device_report.SsoHome.SsoHomeReport',
  'trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg',
  'trpc.group.long_msg_interface.MsgService.SsoSendLongMsg',
  'trpc.group_pro.msgproxy.sendmsg',
  'trpc.group_pro.synclogic.SyncLogic.SyncFirstView',
  'trpc.login.ecdh.EcdhService.SsoKeyExchange',
  'trpc.login.ecdh.EcdhService.SsoNTLoginAuthCodeLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginAuthLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginAuthNewDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginCheckA1List',
  'trpc.login.ecdh.EcdhService.SsoNTLoginCheckGateWayCode',
  'trpc.login.ecdh.EcdhService.SsoNTLoginCheckSms',
  'trpc.login.ecdh.EcdhService.SsoNTLoginCheckThirdCode',
  'trpc.login.ecdh.EcdhService.SsoNTLoginEasyLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginEasyLoginUnusualDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginGetSaltList',
  'trpc.login.ecdh.EcdhService.SsoNTLoginGetSms',
  'trpc.login.ecdh.EcdhService.SsoNTLoginOptimusLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginNewDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginPasswordLoginUnusualDevice',
  'trpc.login.ecdh.EcdhService.SsoNTLoginRapidLogin',
  'trpc.login.ecdh.EcdhService.SsoNTLoginRefreshA2',
  'trpc.login.ecdh.EcdhService.SsoNTLoginRefreshTicket',
  'trpc.login.ecdh.EcdhService.SsoNTLoginTGTExchangeFastLogin',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916a',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916b',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916c',
  'trpc.login.ecdh.EcdhService.SsoOIDB0x916d',
  'trpc.login.ecdh.EcdhService.SsoQRLoginAuthQr',
  'trpc.login.ecdh.EcdhService.SsoQRLoginCancleQr',
  'trpc.login.ecdh.EcdhService.SsoQRLoginGenQr',
  'trpc.login.ecdh.EcdhService.SsoQRLoginRejectQr',
  'trpc.login.ecdh.EcdhService.SsoQRLoginScanQr',
  'trpc.lplan.feed_svr.StatusWrite.SsoComment',
  'trpc.lplan.feed_svr.StatusWrite.SsoPostStatus',
  'trpc.lplan.feed_svr.StatusWrite.SsoReply',
  'trpc.lplan.like_svr.Like.SsoDoLike',
  'trpc.lplan.map_svr.Map.SsoReportLocation',
  'trpc.lplan.user_manager_svr.User.SsoLogin',
  'trpc.lplan.user_manager_svr.User.SsoSetProfile',
  'trpc.metaverse.mob_proxy_svr.MobProxy.SsoHandle',
  'trpc.msg.msg_svc.MsgService.SsoC2CRecallMsg',
  'trpc.msg.msg_svc.MsgService.SsoGetPeerSeq',
  'trpc.msg.msg_svc.MsgService.SsoReadedReport',
  'trpc.msg.olpush.OlPushService.SsoPushAck',
  'trpc.msg.register_proxy.RegisterProxy.PushParams',
  'trpc.msg.register_proxy.RegisterProxy.SsoInfoSync',
  'trpc.o3.ecdh_access.EcdhAccess.SsoEstablishShareKey',
  'trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access',
  'trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish',
  'trpc.o3.ecdh_access.EcdhAccess.SsoSecureAccess',
  'trpc.o3.report.Report.SsoReport',
  'trpc.passwd.manager.PasswdManager.SetPasswd',
  'trpc.passwd.manager.PasswdManager.VerifyPasswd',
  'trpc.qlive.qlive_proxy_svr.TrpcProxy.*',
  'trpc.qlive.relationchain_svr.RelationchainSvr.Follow',
  'trpc.qlive.word_svr.WordSvr.NewPublicChat',
  'trpc.qmeta.mob_proxy_svr.MobProxy.SsoHandle',
  'trpc.qpay.encryptedtransfer.Encryption.SsoUINEncrypt',
  'trpc.qpay.midas_order.Order.SsoMakeOrder',
  'trpc.qpay.red_pack_skin.Skin.SsoAddSkin',
  'trpc.qpay.sso.web.Do',
  'trpc.qq_new_tech.status_svc.StatusService.Register',
  'trpc.qq_new_tech.status_svc.StatusService.SetStatus',
  'trpc.qq_new_tech.status_svc.StatusService.SsoHeartBeat',
  'trpc.qq_new_tech.status_svc.StatusService.UnRegister',
  'trpc.qqhb.qqhb_proxy.Handler.sso_handle',
  'trpc.qqstranger.common_proxy.CommonProxy.SsoHandle',
  'trpc.qqva.vipdata.Vipdata.SsoGetUserData',
  'trpc.springfestival.redpacket.LuckyBag.SsoSubmitGrade',
  'wtlogin.device_lock',
  'wtlogin.exchange_emp',
  'wtlogin.log_report',
  'wtlogin.login',
  'wtlogin.name2uin',
  'wtlogin.qrlogin',
  'wtlogin.register',
  'wtlogin.trans_emp',
  'wtlogin_device.login',
  'wtlogin_device.tran_sim_emp',
]

// per-platform 签名白名单。三端 NT (Linux 3.2.28 / macOS 7.0.0 / Windows 9.9.33) 的本地静态 sign
// 白名单 IDA 实证**完全一致 = LINUX_STATIC_SIGN 的 99 条**。
//
// 订正 (2026-09-25): 早前把 Linux 记成 97 是提取 bug —— sub_56D2D00 里 wtlogin.trans_emp /
// OidbSvcTcp.0x102a 的 libc++ SSO 长度前缀恰为 0x22 (=17<<1='"'), 在反编译 strcpy 字面量里
// 写作转义 \", 被旧正则漏掉。补回后 Linux 也是 99, 与 mac/win 逐字节同。故 trans_emp 是**静态**
// 成员 (走本地分支签名, 删 MMKV 照签), 之前追的 "o3 动态名单" 是这个误数导致的乌龙: gate 实测
// o3 分支从未加过任何 beyond-99 的 cmd, 本地 MMKV nt_mmkv_o3 override 实际空、非网络下发。
//
// 但**实际生效的不是这 99 条**: 2026-09-30 (697592df) 收敛到 99 之后会话照旧被 KickNT, 过度签
// 不是元凶, 2026-10-09 把旧超集整份放回来排除这个变量。生效集 = 旧 532 ∪ 真机 99 = 536 条。
// 取并集而非纯 532: 99 里有 4 条旧超集没收 (0xcd5_0 / 0xdc2_58 / 0xdc2_59 / SsoOIDB0x9689),
// 丢掉等于又悄悄改一次签名行为。
//
// 跟真机的已知偏离 (恢复超集的代价, 想对齐真机就把 EFFECTIVE_SIGN 换回 LINUX_STATIC_SIGN):
//   - InfoSync (RegisterProxy.SsoInfoSync) / status_svc.SsoHeartBeat 真机裸发不签, 这里会签
//   - 0x116d_1 真机抓包无 f24 (见 telemetry.ts), 这里会签
//   - 媒体/群文件/踢人/fetchGroups 等 ~24 条业务 cmd 同属过度签
// Heartbeat.Alive / QQClubComm.getNewFlag / RedTouchSvc.ClientReport / SsoGetConfig / 0x9067_202
// 两份名单都没有, 仍是裸发。
// watch: 未单独抽取, 沿用同一份; watch trans_emp 由调用点 skipSign 排除。
const EFFECTIVE_SIGN: ReadonlySet<string> = new Set([...LEGACY_SIGN_SUPERSET, ...LINUX_STATIC_SIGN])

export const SIGN_REQUIRED: Record<ProtocolName, ReadonlySet<string>> = {
  linux: EFFECTIVE_SIGN,
  windows: EFFECTIVE_SIGN,
  macos: EFFECTIVE_SIGN,
  watch: EFFECTIVE_SIGN,
}

/** 该 cmd 在当前平台是否需要签名。发包统一走这里判定。 */
export function cmdNeedsSign(cmd: string, platform: ProtocolName): boolean {
  return SIGN_REQUIRED[platform]?.has(cmd) ?? false
}
